trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    Major: 1
    Minor: 0
    BuildConfiguration: release
    Projects: '**/*.csproj'
    OpenApiFilename: 'RestArchiveService-v1.0.json'
name: $(Major).$(Minor).$(Rev:r)
steps:
- script: dotnet tool install --global dotnet-xdt
  displayName: Install XDT tool
- task: DotNetCoreCLI@2
  displayName: install swagger.cli
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install swashbuckle.aspnetcore.cli --version 5.0.0'
- task: DotNetCoreCLI@2
  displayName: Build for OpenAPI docs generation
  inputs:
    command: 'build'
    projects: $(Projects)
    arguments: '--configuration $(BuildConfiguration) -o $(Build.BinariesDirectory)/openapi'
- task: DotNetCoreCLI@2
  displayName: Create OpenAPI docs
  inputs:
    command: 'custom'
    custom: 'swagger'
    arguments: 'tofile --host "http://example.com" --output $(Build.BinariesDirectory)/openapi/$(OpenApiFilename) $(Build.BinariesDirectory)/openapi/OneTooXRestArchiveTest.dll v1.0'
# Copy of file is necessary as dotnet swagger tofile cannot create a new folder
- task: CopyFiles@2
  displayName: Copy OpenAPI docs to artifacts
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)/openapi'
    Contents: '$(OpenApiFilename)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/openapi'
- script: dotnet xdt --source web.config --transform Web.Release.config --output web.config
  displayName: Transform web.config
- task: DotNetCoreCLI@2
  displayName: publish for webdeploy
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r win-x64 -o $(Build.ArtifactStagingDirectory)/WinWebDeploy/'
- task: DotNetCoreCLI@2
  displayName: publish windows
  inputs:
    command: 'publish'
    arguments: '-r win-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.BinariesDirectory)/win/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: zip win files
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/win'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/RestArchiveService-$(Build.BuildNumber)-win-x64.zip'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  displayName: Publish linux
  inputs:
    command: 'publish'
    arguments: '-r linux-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.BinariesDirectory)/linux/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: zip linux files
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/linux'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/RestArchiveService-$(Build.BuildNumber)-linux-x64.zip'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  displayName: Publish osx
  inputs:
    command: 'publish'
    arguments: '-r osx-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.BinariesDirectory)/osx/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: zip osx files
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/osx'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/RestArchiveService-$(Build.BuildNumber)-osx-x64.zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Package