trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    Major: 1
    Minor: 0
    BuildConfiguration: release
    Projects: '**/*.csproj'
name: $(Major).$(Minor).$(Rev:r)
steps:
- task: DotNetCoreCLI@2
  displayName: install swagger.cli
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install swashbuckle.aspnetcore.cli --version 5.0.0'
- task: DotNetCoreCLI@2
  displayName: Build for OpenAPI docs generation
  inputs:
    command: 'build'
    projects: $(Projects)
    arguments: '--configuration $(BuildConfiguration) -o $(Build.BinariesDirectory)/openapi'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'swagger'
    arguments: 'tofile --host "http:example.com" --outputfile $(Build.ArtifactStagingDirectory)/openapi/RestArchiveService-v1.0.json $(Build.BinariesDirectory)/openapi/OneTooXRestArchiveTest.dll v1.0'
- task: DotNetCoreCLI@2
  displayName: publish windows
  inputs:
    command: 'publish'
    arguments: '-r win-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.BinariesDirectory)/win/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: zip win files
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/win'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/RestArchiveService-$(Build.BuildNumber)-win-x64.zip'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  displayName: Publish linux
  inputs:
    command: 'publish'
    arguments: '-r linux-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.BinariesDirectory)/linux/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: zip linux files
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/linux'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/RestArchiveService-$(Build.BuildNumber)-linux-x64.zip'
    replaceExistingArchive: true
- task: DotNetCoreCLI@2
  displayName: Publish osx
  inputs:
    command: 'publish'
    arguments: '-r osx-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.BinariesDirectory)/osx/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: zip osx files
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/osx'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/RestArchiveService-$(Build.BuildNumber)-osx-x64.zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathToPublish: 
    artifactName: Package