trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    major: 1
    minor: 0
name: $(major).$(minor).$(Rev:r)
steps:
- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: 'OneTooXRestArchiveTest.csproj'
- task: DotNetCoreCLI@2
  displayName: publish windows
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-r win-x64 --self-contained false /p:PublishSingleFile=true'
- task: DotNetCoreCLI@2
  displayName: Publish linux
  inputs:
    command: 'publish'
    arguments: '-r linux-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.ArtifactStagingDirectory)/linux/'
    zipAfterPublish: false
- task: DotNetCoreCLI@2
  displayName: Publish osx
  inputs:
    command: 'publish'
    arguments: '-r osx-x64 --self-contained false /p:PublishSingleFile=true /p:AssemblyName=RestArchiveService -o $(Build.ArtifactStagingDirectory)/osx/'
    zipAfterPublish: false
    modifyOutputPath: false
- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Package